model-name: "my_denoiser"
use-direct-denoiser: True
data:
  save-path: "data"
  paths: "data"
  patterns: "*.tif"
  axes: "SYX"
  number-dimensions: 2
  # Set a patch size if raw images are all different shapes
  patch-size: null
  clip-outliers: False
predict-parameters:
  batch-size: 1
memory:
  precision: "bf16-mixed"
  gpu: [0]