model-name: "my_denoiser"
data:
  paths: "data"
  patterns: "*.tif"
  axes: "SYX"
  number-dimensions: 2
  patch-size: null
  clip-outliers: False
train-parameters:
  max-time: "00:24:00:00"
  max-epochs: 1000
  patience: 100
  batch-size: 4
  number-grad-batches: 4
  crop-size: [256, 256]
  training-split: 0.9
  use-direct-denoiser: True
  direct-denoiser-loss: "MSE"
hyper-parameters:
  noise-direction: "x"
  s-code-channels: 128
  scale-initialisation: False
  number-layers: 14
  number-components: 8
  discretised: False
memory:
  precision: "bf16-mixed"
  checkpointed: False
  gpu: [0]
